exports.privacyPolicy = 
`
Privacy Policy for Nomi \n 
Last updated: November 06, 2024 
This Privacy Policy describes Our policies and procedures on the collection, use and disclosure 
of Your information when You use the Service and tells You about Your privacy rights and how 
the law protects You. 
We use Your Personal data to provide and improve the Service. By using the Service, You agree 
to the collection and use of information in accordance with this Privacy Policy.  
Interpretation and Definitions 
Interpretation 
The words of which the initial letter is capitalized have meanings defined under the following 
conditions. The following definitions shall have the same meaning regardless of whether they 
appear in singular or in plural. 
Definitions 
For the purposes of this Privacy Policy: 
• Account means a unique account created for You to access our Service or parts of our 
Service. 
• Affiliate means an entity that controls, is controlled by or is under common control with 
a party, where "control" means ownership of 50% or more of the shares, equity interest or 
other securities entitled to vote for election of directors or other managing authority. 
• Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) 
refers to Nomi, 43013 Ashley Heights Circle, Ashburn. 
• Cookies are small files that are placed on Your computer, mobile device or any other 
device by a website, containing the details of Your browsing history on that website 
among its many uses. 
• Country refers to: Virginia, United States 
• Device means any device that can access the Service such as a computer, a cellphone or a 
digital tablet. 
• Personal Data is any information that relates to an identified or identifiable individual. 
Nomi collects customer name information, email addresses, as well transaction and 
account history for caching.  
• Service refers to the Website. 
• Service Provider means any natural or legal person who processes the data on behalf of 
the Company. It refers to third-party companies or individuals employed by the Company 
to facilitate the Service, to provide the Service on behalf of the Company, to perform 
services related to the Service or to assist the Company in analyzing how the Service is 
used. 
• Usage Data refers to data collected automatically, either generated by the use of the 
Service or from the Service infrastructure itself (for example, the duration of a page 
visit). 
• Website refers to Nomi, accessible from https://domain-na 
• You means the individual accessing or using the Service, or the company, or other legal 
entity on behalf of which such individual is accessing or using the Service, as applicable. 
Collecting and Using Your Personal Data 
Types of Data Collected 
Personal Data 
While using Our Service, We may ask You to provide Us with certain personally identifiable 
information that can be used to contact or identify You. Personally identifiable information may 
include, but is not limited to: 
• Email address 
• Name 
• Usage Data 
• Financial Data (to you discretion including) 
o Bank Account balances and limits 
o Credit card balances 
o Income statements 
o Transaction histories 
o Investment histories  
Usage Data 
Usage Data is collected automatically when using the Service. 
Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP 
address), browser type, browser version, the pages of our Service that You visit, the time and 
date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic 
data. 
When You access the Service by or through a mobile device, We may collect certain information 
automatically, including, but not limited to, the type of mobile device You use, Your mobile 
device unique ID, the IP address of Your mobile device, Your mobile operating system, the type 
of mobile Internet browser You use, unique device identifiers and other diagnostic data. 
We may also collect information that Your browser sends whenever You visit our Service or 
when You access the Service by or through a mobile device. 
Tracking Technologies and Cookies 
We use Cookies and similar tracking technologies to track the activity on Our Service and store 
certain information. Tracking technologies used are beacons, tags, and scripts to collect and track 
information and to improve and analyze Our Service. The technologies We use may include: 
• Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can 
instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. 
However, if You do not accept Cookies, You may not be able to use some parts of our 
Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our 
Service may use Cookies. 
• Web Beacons. Certain sections of our Service and our emails may contain small 
electronic files known as web beacons (also referred to as clear gifs, pixel tags, and 
single-pixel gifs) that permit the Company, for example, to count users who have visited 
those pages or opened an email and for other related website statistics (for example, 
recording the popularity of a certain section and verifying system and server integrity). 
Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal 
computer or mobile device when You go offline, while Session Cookies are deleted as soon as 
You close Your web browser. You can learn more about cookies on TermsFeed website article. 
We use both Session and Persistent Cookies for the purposes set out below: 
• Necessary / Essential Cookies 
Type: Session Cookies 
Administered by: Us 
Purpose: These Cookies are essential to provide You with services available through the Website 
and to enable You to use some of its features. They help to authenticate users and prevent 
fraudulent use of user accounts. Without these Cookies, the services that You have asked for 
cannot be provided, and We only use these Cookies to provide You with those services. 
• Cookies Policy / Notice Acceptance Cookies 
Type: Persistent Cookies 
Administered by: Us 
Purpose: These Cookies identify if users have accepted the use of cookies on the Website. 
• Functionality Cookies 
Type: Persistent Cookies 
Administered by: Us 
Purpose: These Cookies allow us to remember choices You make when You use the Website, 
such as remembering your login details or language preference. The purpose of these Cookies is 
to provide You with a more personal experience and to avoid You having to re-enter your 
preferences every time You use the Website. 
For more information about the cookies we use and your choices regarding cookies, please visit 
our Cookies Policy or the Cookies section of our Privacy Policy. 
Use of Your Personal Data 
The Company may use Personal Data for the following purposes: 
• To provide and maintain our Service, including to monitor the usage of our Service. 
• To manage Your Account: to manage Your registration as a user of the Service. The 
Personal Data You provide can give You access to different functionalities of the Service 
that are available to You as a registered user. 
• To contact You: To contact You by email, telephone calls, SMS, or other equivalent 
forms of electronic communication, such as a mobile application's push notifications 
regarding updates or informative communications related to the functionalities, products 
or contracted services, including the security updates, when necessary or reasonable for 
their implementation. 
• To provide You with news, special offers and general information about other goods, 
services and events which we offer that are similar to those that you have already 
purchased or enquired about unless You have opted not to receive such information. 
• To manage Your requests: To attend and manage Your requests to Us.  
• For other purposes: We may use Your information internally for other purposes, such as 
data analysis, identifying usage trends, determining the effectiveness of our promotional 
campaigns and to evaluate and improve our Service, products, services, marketing and 
your experience. 
Retention of Your Personal Data 
1. Purpose 
This policy ensures Nomi adheres to applicable data privacy laws by defining our approach to 
the retention and deletion of user data. 
2. Scope 
This policy applies to all user data, including but not limited to personal information, transaction 
data, and bank account details, that is collected as part of using Nomi's services. 
3. Data Retention 
User data will be retained only as long as it is needed for legitimate business purposes, including 
delivering services, fulfilling legal or regulatory obligations, and resolving disputes. Transaction 
and account data will be retained for a period of [one year] after the user's last interaction unless 
the user requests deletion sooner. Users can request deletion by terminating their account with 
Nomi – this is made clear to the user upon creating an account. 
4. Data Deletion 
Users may request deletion of their personal information at any time by contacting at 
[saivamsim26@gmail.com] or by deleting their Nomi account. Upon receiving a deletion 
request, we will delete the user's data within 1 week and confirm the deletion with the user. 
Regular audits will be conducted to ensure compliance with this policy. 
5. Compliance 
This policy will be reviewed periodically to ensure compliance with relevant data protection 
laws, including GDPR and CCPA, and will be updated as required to reflect changes in 
regulatory requirements. 
Transfer of Your Personal Data 
Your information, including Personal Data, is processed at the Company's operating offices and 
in any other places where the parties involved in the processing are located. It means that this 
information may be transferred to — and maintained on — computers located outside of Your 
state, province, country or other governmental jurisdiction where the data protection laws may 
differ than those from Your jurisdiction. 
Your consent to this Privacy Policy followed by Your submission of such information represents 
Your agreement to that transfer. 
The Company will take all steps reasonably necessary to ensure that Your data is treated securely 
and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place 
to an organization or a country unless there are adequate controls in place including the security 
of Your data and other personal information. 
Delete Your Personal Data 
You have the right to delete or request that We assist in deleting the Personal Data that We have 
collected about You. 
Our Service may give You the ability to delete certain information about You from within the 
Service. 
You may update, amend, or delete Your information at any time by signing in to Your Account, if 
you have one, and visiting the account settings section that allows you to manage Your personal 
information. You may also contact Us to request access to, correct, or delete any personal 
information that You have provided to Us. 
Please note, however, that We may need to retain certain information when we have a legal 
obligation or lawful basis to do so. 
Disclosure of Your Personal Data 
Business Transactions 
If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be 
transferred. We will provide notice before Your Personal Data is transferred and becomes subject 
to a different Privacy Policy. 
Law enforcement 
Under certain circumstances, the Company may be required to disclose Your Personal Data if 
required to do so by law or in response to valid requests by public authorities (e.g. a court or a 
government agency). 
Other legal requirements 
The Company may disclose Your Personal Data in the good faith belief that such action is 
necessary to: 
• Comply with a legal obligation 
• Protect and defend the rights or property of the Company 
• Prevent or investigate possible wrongdoing in connection with the Service 
• Protect the personal safety of Users of the Service or the public 
• Protect against legal liability 
Security of Your Personal Data 
The security of Your Personal Data is important to Us, but remember that no method of 
transmission over the Internet, or method of electronic storage is 100% secure. While We strive 
to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its 
absolute security. 
Links to Other Websites 
Our Service may contain links to other websites that are not operated by Us. If You click on a 
third party link, You will be directed to that third party's site. We strongly advise You to review 
the Privacy Policy of every site You visit. 
We have no control over and assume no responsibility for the content, privacy policies or 
practices of any third party sites or services. 
Changes to this Privacy Policy 
We may update Our Privacy Policy from time to time. We will notify You of any changes by 
posting the new Privacy Policy on this page. 
You are advised to review this Privacy Policy periodically for any changes. Changes to this 
Privacy Policy are effective when they are posted on this page. 
Contact Us 
If you have any questions about this Privacy Policy, You can contact us: 
• By email: sophia@nomifinance.com 

`